<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>eu.prismacapacity</groupId>
    <artifactId>basepom-oss</artifactId>
    <version>0.2.18</version>
  </parent>
  <artifactId>cqs</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <description>Simple abstractions to communicate within one process
    following the CQS principle.</description>
  <url>https://github.com/prisma-capacity</url>
  <organization>
    <name>PRISMA European Capacity Platform GmbH</name>
    <url>http://www.prisma-capacity.eu</url>
  </organization>
  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <issueManagement>
    <system>github</system>
    <url>https://github.com/prisma-capacity/cqs/issues</url>
  </issueManagement>
  <scm>
    <connection>scm:git:http://github.com/prisma-capacity/cqs.git</connection>
    <developerConnection>scm:git:ssh://github.com/prisma-capacity/cqs.git</developerConnection>
    <url>https://github.com/prisma-capacity/cqs</url>
  </scm>
  <modules>
    <module>cqs-core</module>
  </modules>
  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.version>3.3.9</maven.version>
    <lombok.version>1.18.46</lombok.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <plugins>
      <!-- TODO -->
    </plugins>
  </build>
</project>
